def get_place_master():
    place_dict={"01":"kiryu"
                ,"02":"toda"
                ,"03":"edogawa"
                ,"04":"heiwazima"
                ,"05":"tamagawa"
                ,"06":"hamanako"
                ,"07":"gamagori"
                ,"08":"tokoname"
                ,"09":"tu"
                ,"10":"mikuni"
                ,"11":"biwako"
                ,"12":"suminoe"
                ,"13":"amagasaki"
                ,"14":"naruto"
                ,"15":"marugame"
                ,"16":"kozima"
                ,"17":"miyazima"
                ,"18":"tokuyama"
                ,"19":"simonoseki"
                ,"20":"wakamatu"
                ,"21":"asiya"
                ,"22":"fukuoka"
                ,"23":"karatu"
                ,"24":"omura"}
    return place_dict

def get_place_num_master():
    place_num_dict={1:"kiryu"
                ,2:"toda"
                ,3:"edogawa"
                ,4:"heiwazima"
                ,5:"tamagawa"
                ,6:"hamanako"
                ,7:"gamagori"
                ,8:"tokoname"
                ,9:"tu"
                ,10:"mikuni"
                ,11:"biwako"
                ,12:"suminoe"
                ,13:"amagasaki"
                ,14:"naruto"
                ,15:"marugame"
                ,16:"kozima"
                ,17:"miyazima"
                ,18:"tokuyama"
                ,19:"simonoseki"
                ,20:"wakamatu"
                ,21:"asiya"
                ,22:"fukuoka"
                ,23:"karatu"
                ,24:"omura"}
    return place_num_dict
